apiVersion: v1 
kind: Service 
metadata: 
 name: redis
 namespace: roboshop  
spec: 
 type: {{ .Values.service.type}}
 selector: 
   project: roboshop
   component: redis
   tier: db 
 ports: 
  - protocol: TCP 
    port: 6379 # Service port 
    targetPort: 6379 # Container port 
    